### ISSUE TITLE
データベースの画像型でUploadFile型をシリアライズしようとしてコケます

### ISSUE THREAD

**Issue by modeverv** [opensource-workshop/connect-cms#1690]
## 概要
UploadFile型をセッション系がシリアライズしようとしてコケてます
- データベースに画像型を登録
- レコードの追加を試み
- 確認画面遷移時にエラー
- 
## 実行環境
OS: docker on mac
ブラウザ: chrome 
Connect-CMS: master 2023/6/6時点
php version: 7.4

## 再現手順
- データベースに画像型を登録
- レコードの追加を試み
- 確認画面遷移時にエラー

## スクリーンショット
![スクリーンショット 2023-06-06 11 34 43](https://github.com/opensource-workshop/connect-cms/assets/115578/91985b8c-8238-45de-acff-e6e9a363ea7f)

```
[2023-06-06 11:34:23] development.ERROR: Serialization of 'Illuminate\Http\UploadedFile' is not allowed {"userId":1,"exception":"[object] (Exception(code: 0): Serialization of 'Illuminate\\Http\\UploadedFile' is not allowed at /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Session/Store.php:129)
[stacktrace]
#0 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Session/Store.php(129): serialize(Array)
#1 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(236): Illuminate\\Session\\Store->save()
#2 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(130): Illuminate\\Session\\Middleware\\StartSession->saveSession(Object(Illuminate\\Http\\Request))
#3 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#4 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#5 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#6 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#12 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#13 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#14 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#15 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/html/connect-cms/app/Http/Middleware/ResponseHeader.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ResponseHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/html/connect-cms/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#33 /var/www/html/connect-cms/public/index.php(59): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#34 {main}
"} 
```

**Comment by modeverv** [comment]
ちょっとソース見てるのですが、
Sotre.phpでddすると
oldにuploadfileがいます。
```
^ array:14 [▼
  "_token" => "cesqF3bax9bZPFK16ZeVTlfDRYS9A40r22pXxweb"
  "_flash" => array:2 [▶]
  "_previous" => array:1 [▶]
  "login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d" => 1
  "auth" => array:1 [▶]
  "calendar_year13" => "2023"
  "calendar_month13" => "06"
  "calendar_day13" => "01"
  "holiday_year" => "2023"
  "search_keyword" => array:1 [▶]
  "opac_search_type" => array:1 [▶]
  "opac_search_sort_type" => array:1 [▶]
  "opac_search_view_count" => array:1 [▶]
  "_old_input" => array:6 [▼
    "_token" => "cesqF3bax9bZPFK16ZeVTlfDRYS9A40r22pXxweb"
    "databases_columns_value" => array:4 [▼
      1 => "テスト"
      2 => null
      3 => "<p>aaaaaa</p>"
      4 => Illuminate\Http\UploadedFile {#1325 ▼
        -test: false
        -originalName: "chino.gif"
        -mimeType: "image/gif"
        -error: 0
        #hashName: null
        path: "/tmp"
        filename: "phpUovdtX"
        basename: "phpUovdtX"
        pathname: "/tmp/phpUovdtX"
        extension: ""
        realPath: "/tmp/phpUovdtX"
        aTime: 2023-06-06 12:45:21
        mTime: 2023-06-06 12:45:20
        cTime: 2023-06-06 12:45:20
        inode: 2624284
        size: 2081979
        perms: 0100600
        owner: 33
        group: 33
        type: "file"
        writable: true
        readable: true
        executable: false
        file: true
        dir: false
        link: false
      }
    ]
    "posted_at" => "2023-06-06 12:45"
    "expires_at" => null
    "display_sequence" => null
    "categories_id" => null
  ]
]
```

```
    /**
     * Save the session data to storage.
     *
     * @return void
     */
    public function save()
    {
        $this->ageFlashData();

        dd($this->attributes); // tmp ikehata
        $this->handler->write($this->getId(), $this->prepareForStorage(
            serialize($this->attributes)
        ));

        $this->started = false;
    }
```

ちょっとプログラムまだ追いきれてないのですが(どこせSessionに突っ込んでいるのかまだわからない。。
バリデーションに引っかかった時以外でも
uploadfile型を抜かないとダメなのかも？とか思ってます。。

**Comment by gakigaki** [comment]
#1171 でも報告があり原因が特定できていないバグのようです。

調査のため、以下ご回答いただけますか？

- 同一ページ内に他のフレームを配置していますか？配置してる場合はどのプラグインを配置していますか？

**Comment by modeverv** [comment]
はい、置いています。
最小の再現手順を調査しましたので下記します。

1. ヘッダー部にデータベースを配置
2. メインにデータベースを配置
3. メインにOPACを配置

ヘッダー部とメイン部のデータベース部品は同じデータベースを選択しています。

メイン部データベースにレコードを新規追加試行→成功
ヘッダー部データベースに新規追加試行→エラー
opacがなければヘッダー部は通ります。

https://github.com/opensource-workshop/connect-cms/assets/115578/b92f1647-6ad4-40db-a6eb-516fa4a888c5
↑動画
私の方でも引き続きソースを読んでいきます。

最低の逃げの手段ですが、下記ソースをSession.phpでやると一応回避はできますが絶対に採用したくないアプローチです。。
\Illuminate\Session\Store::save

```php
    public function save()
    {
        $this->ageFlashData();

        //dump($this->attributes);
        //dump($this->attributes);
        foreach ($this->attributes as $key => $value) {
            if($key === '_old_input') {
                foreach($value as $key2 => $value2) {
                    if($key2 === "databases_columns_value") {
                        foreach($value2 as $key3 => $value3) {
                            if($value3 instanceof \Illuminate\Http\UploadedFile) {
                                unset($this->attributes['_old_input']['databases_columns_value'][$key3]);
                            }
                        }
                    }
                }
            }
        }
        //dump($this->attributes);

        $this->handler->write($this->getId(), $this->prepareForStorage(
            serialize($this->attributes)
        ));

        $this->started = false;
    }
```

**Comment by modeverv** [comment]
一旦動作しなくなると思いますが、`\App\Plugins\User\Opacs\OpacsPlugin::index`の
$request->flashをコメントアウトすると動作するようになりました。さてどうやって直しましょうね。
connect-cms歴1日なのでよくわかりません!
```
    /**
     * 書誌データ取得関数
     *
     * @return view
     * @method_title 書籍一覧
     * @method_desc 書籍を検索し、一覧表示できます。
     * @method_detail
     */
    public function index($request, $page_id, $frame_id, $errors = null, $messages = null)
    {
        // セッション初期化などのLaravel 処理。
        //$request->flash();
```

**Comment by modeverv** [comment]
一旦私の確認範囲では下記コードでエラーは回避しつつ、OPACの検索も動くようになります。
$request->flashをプロジェクト独自のものに差し替えたりして動かした方が良さそうにおもいます。
ご検討ください。
そして他にも同様の箇所はたくさんありそうです。調べていないのでわかりません。
```
    /**
     * 書誌データ取得関数
     *
     * @return view
     * @method_title 書籍一覧
     * @method_desc 書籍を検索し、一覧表示できます。
     * @method_detail
     */
    public function index(Request $request, $page_id, $frame_id, $errors = null, $messages = null)
    {
        $flashExcepts = [];
        $databases_columns = $request->only(["databases_columns_value"]);
        foreach ($databases_columns as $key => $value) {
            foreach($value as $key2 => $value2) {
                if($value2 instanceof \Illuminate\Http\UploadedFile) {
                    $flashExcepts[] = "databases_columns_value." . $key2;
                }
            }
        }
        $request->flashExcept($flashExcepts);
        // セッション初期化などのLaravel 処理。        
        //$request->flash();
```

**Comment by akagane99** [comment]
* 調査ありがとうございます。上記でも直りますね。
    * できればデータベースの修正をopacに入れたくないなと。
* クローズしたissueを探してみたら下記がありました。いまのopacのindexの作りが悪いので、今後下記修正が反映された直ると思います。
    * https://github.com/opensource-workshop/connect-cms/issues/882
* 暫定対応
    * あとは同じページでデータベースとOPACを一緒に使わなければ、当エラーを回避できると思います。

**Comment by modeverv** [comment]
> できればデータベースの修正をopacに入れたくないなと。

おっしゃる通りです。プラグインの形式で分離している意味がなくなりますね。
フラッシュアイデアですが、opac部品のPOSTにqueryパラメーターを付与してその場合だけopacの中でカスタムした私のようなopacに必要な内容以外は削除してflashという手法を考えました。それならばまだ言い訳として成り立つかな。。とか思いました。

一旦手元は現状対応で誤魔化しておき、#882 の対応をお待ちします。
