### ISSUE TITLE
【OPAC】設定新規登録でエラー

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#948]
## 画面

![image](https://user-images.githubusercontent.com/2756509/127412636-1c0a9e9d-159e-41eb-a0c7-560a731ea214.png)

## エラーログ

```
[previous exception] [object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'request_mail_send_flag' cannot be null (SQL: insert into `opacs` (`bucket_id`, `opac_name`, `view_count`, `moderator_mail_send_flag`, `moderator_mail_send_address`, `request_mail_send_flag`, `lent_setting`, `lent_limit`, `updated_at`, `created_at`) values (39, 1, 1, 0, ?, ?, 0, 0, 2021-07-29 08:56:58, 2021-07-29 08:56:58)) at C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:669)
[stacktrace]
#0 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('insert into `op...', Array, Object(Closure))
#1 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(464): Illuminate\\Database\\Connection->run('insert into `op...', Array, Object(Closure))
#2 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(416): Illuminate\\Database\\Connection->statement('insert into `op...', Array)
#3 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Processors\\Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `op...', Array)
#4 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2705): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into `op...', Array, 'id')
#5 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(1385): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(840): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(805): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(668): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Plugins\\User\\Opacs\\OpacsPlugin.php(797): Illuminate\\Database\\Eloquent\\Model->save()
#10 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Plugins\\User\\UserPluginBase.php(268): App\\Plugins\\User\\Opacs\\OpacsPlugin->saveBuckets(Object(Illuminate\\Http\\Request), 1, 45, NULL)
#11 C:\\projects\\connect-cms\\htdocs\\connect-cms\\storage\\framework\\views\\251cb48feebdac447872dc72618515d13c420f49.php(108): App\\Plugins\\User\\UserPluginBase->invoke(Object(App\\Plugins\\User\\Opacs\\OpacsPlugin), Object(Illuminate\\Http\\Request), 'saveBuckets', 1, 45, NULL)
#12 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php(43): include('C:\\\\projects\\\\con...')
#13 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('C:\\\\projects\\\\con...', Array)
#14 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\facade\\ignition\\src\\Views\\Engines\\CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('C:\\\\projects\\\\con...', Array)
#15 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('C:\\\\projects\\\\con...', Array)
#16 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(126): Illuminate\\View\\View->getContents()
#17 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(91): Illuminate\\View\\View->renderContents()
#18 C:\\projects\\connect-cms\\htdocs\\connect-cms\\storage\\framework\\views\\3374a1a2fbf094984a198e77c84a5c19dbb47bb2.php(109): Illuminate\\View\\View->render()
#19 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php(43): include('C:\\\\projects\\\\con...')
#20 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('C:\\\\projects\\\\con...', Array)
#21 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\facade\\ignition\\src\\Views\\Engines\\CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('C:\\\\projects\\\\con...', Array)
#22 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('C:\\\\projects\\\\con...', Array)
#23 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(126): Illuminate\\View\\View->getContents()
#24 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(91): Illuminate\\View\\View->renderContents()
#25 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php(42): Illuminate\\View\\View->render()
#26 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\symfony\\http-foundation\\Response.php(205): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#27 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(749): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 200, Array)
#28 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(721): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#29 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#30 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Http\\Middleware\\ConnectFrame.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\ConnectFrame->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Http\\Middleware\\ConnectPagePassword.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\ConnectPagePassword->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Http\\Middleware\\ConnectPage.php(162): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\ConnectPage->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Http\\Middleware\\ConnectLog.php(232): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\ConnectLog->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Http\\Middleware\\ConnectInit.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\ConnectInit->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#56 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#57 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#58 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#59 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#60 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 C:\\projects\\connect-cms\\htdocs\\connect-cms\\app\\Http\\Middleware\\ResponseHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\ResponseHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#76 C:\\projects\\connect-cms\\htdocs\\connect-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#77 C:\\projects\\connect-cms\\htdocs\\connect-cms\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#78 {main}
```

**Comment by akagane99** [comment]
対応しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/209f47ff7692e535e3fb215ddb47568cc8c8e778

**Comment by akagane99** [comment]
修正間違いがあったので、再オープンします。

**Comment by akagane99** [comment]
修正間違い直しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/6452317bd06480d9593a93549a2d8df332a627e6
